---
- hosts: localhost 
  become: yes 
  gather_facts: no 
  tasks: 
  vars: 
    host_name : server-web
  tasks:  
  - name: install apache server 
    yum: 
      name: httpd 
      state: present 
  - name: start apache service 
    service: 
      name: httpd 
      state: started 
  - name: copy index page 
    template: 
      src: index.html.j2 
      dest: /var/www/html/index.html 
    notify: httpd restart 
  handlers: 
  - name: httpd restart 
    service: 
      name: httpd
      state: restarted
